// Database types for Supabase
// This file should be regenerated using: npx supabase gen types typescript

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          role: "customer" | "staff" | "admin";
          is_active: boolean;
          pricing_tier_id: string | null;
          stripe_customer_id: string | null;
          avatar_url: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          phone?: string | null;
          role?: "customer" | "staff" | "admin";
          is_active?: boolean;
          pricing_tier_id?: string | null;
          stripe_customer_id?: string | null;
          avatar_url?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          phone?: string | null;
          role?: "customer" | "staff" | "admin";
          is_active?: boolean;
          pricing_tier_id?: string | null;
          stripe_customer_id?: string | null;
          avatar_url?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      addresses: {
        Row: {
          id: string;
          user_id: string;
          label: string | null;
          is_default: boolean;
          first_name: string | null;
          last_name: string | null;
          company: string | null;
          address_line1: string;
          address_line2: string | null;
          city: string;
          state: string;
          postal_code: string;
          country: string;
          phone: string | null;
          delivery_instructions: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          label?: string | null;
          is_default?: boolean;
          first_name?: string | null;
          last_name?: string | null;
          company?: string | null;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          state: string;
          postal_code: string;
          country?: string;
          phone?: string | null;
          delivery_instructions?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          label?: string | null;
          is_default?: boolean;
          first_name?: string | null;
          last_name?: string | null;
          company?: string | null;
          address_line1?: string;
          address_line2?: string | null;
          city?: string;
          state?: string;
          postal_code?: string;
          country?: string;
          phone?: string | null;
          delivery_instructions?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          image_url: string | null;
          parent_id: string | null;
          sort_order: number;
          is_active: boolean;
          meta_title: string | null;
          meta_description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          image_url?: string | null;
          parent_id?: string | null;
          sort_order?: number;
          is_active?: boolean;
          meta_title?: string | null;
          meta_description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          image_url?: string | null;
          parent_id?: string | null;
          sort_order?: number;
          is_active?: boolean;
          meta_title?: string | null;
          meta_description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          name: string;
          slug: string;
          sku: string | null;
          description: string | null;
          short_description: string | null;
          category_id: string | null;
          vendor_id: string | null;
          pricing_type: "fixed" | "weight";
          base_price: number;
          sale_price: number | null;
          cost_price: number | null;
          weight_unit: "lb" | "oz" | "kg" | "g";
          estimated_weight: number | null;
          min_weight: number | null;
          max_weight: number | null;
          price_per_unit: number | null;
          track_inventory: boolean;
          stock_quantity: number;
          low_stock_threshold: number;
          shelf_location: string | null;
          allow_backorder: boolean;
          images: Json;
          featured_image_url: string | null;
          tags: string[];
          is_active: boolean;
          is_featured: boolean;
          is_taxable: boolean;
          meta_title: string | null;
          meta_description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          sku?: string | null;
          description?: string | null;
          short_description?: string | null;
          category_id?: string | null;
          vendor_id?: string | null;
          pricing_type?: "fixed" | "weight";
          base_price: number;
          sale_price?: number | null;
          cost_price?: number | null;
          weight_unit?: "lb" | "oz" | "kg" | "g";
          estimated_weight?: number | null;
          min_weight?: number | null;
          max_weight?: number | null;
          price_per_unit?: number | null;
          track_inventory?: boolean;
          stock_quantity?: number;
          low_stock_threshold?: number;
          shelf_location?: string | null;
          allow_backorder?: boolean;
          images?: Json;
          featured_image_url?: string | null;
          tags?: string[];
          is_active?: boolean;
          is_featured?: boolean;
          is_taxable?: boolean;
          meta_title?: string | null;
          meta_description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          sku?: string | null;
          description?: string | null;
          short_description?: string | null;
          category_id?: string | null;
          vendor_id?: string | null;
          pricing_type?: "fixed" | "weight";
          base_price?: number;
          sale_price?: number | null;
          cost_price?: number | null;
          weight_unit?: "lb" | "oz" | "kg" | "g";
          estimated_weight?: number | null;
          min_weight?: number | null;
          max_weight?: number | null;
          price_per_unit?: number | null;
          track_inventory?: boolean;
          stock_quantity?: number;
          low_stock_threshold?: number;
          shelf_location?: string | null;
          allow_backorder?: boolean;
          images?: Json;
          featured_image_url?: string | null;
          tags?: string[];
          is_active?: boolean;
          is_featured?: boolean;
          is_taxable?: boolean;
          meta_title?: string | null;
          meta_description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          order_number: number;
          user_id: string | null;
          status: "pending" | "confirmed" | "processing" | "packed" | "shipped" | "delivered" | "cancelled";
          payment_status: "pending" | "authorized" | "paid" | "partially_refunded" | "refunded" | "failed";
          fulfillment_type: "pickup" | "delivery" | "shipping";
          fulfillment_location_id: string | null;
          delivery_zone_id: string | null;
          shipping_zone_id: string | null;
          schedule_id: string | null;
          scheduled_date: string | null;
          shipping_address: Json | null;
          billing_address: Json | null;
          subtotal: number;
          discount_amount: number;
          tax_amount: number;
          shipping_fee: number;
          total: number;
          stripe_payment_intent_id: string | null;
          stripe_charge_id: string | null;
          customer_notes: string | null;
          private_notes: string | null;
          invoice_notes: string | null;
          source: string;
          ip_address: string | null;
          user_agent: string | null;
          coupon_id: string | null;
          coupon_code: string | null;
          gift_card_id: string | null;
          gift_card_amount_used: number;
          store_credit_used: number;
          tracking_number: string | null;
          tracking_url: string | null;
          shipped_at: string | null;
          delivered_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number?: number;
          user_id?: string | null;
          status?: "pending" | "confirmed" | "processing" | "packed" | "shipped" | "delivered" | "cancelled";
          payment_status?: "pending" | "authorized" | "paid" | "partially_refunded" | "refunded" | "failed";
          fulfillment_type: "pickup" | "delivery" | "shipping";
          fulfillment_location_id?: string | null;
          delivery_zone_id?: string | null;
          shipping_zone_id?: string | null;
          schedule_id?: string | null;
          scheduled_date?: string | null;
          shipping_address?: Json | null;
          billing_address?: Json | null;
          subtotal?: number;
          discount_amount?: number;
          tax_amount?: number;
          shipping_fee?: number;
          total?: number;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          customer_notes?: string | null;
          private_notes?: string | null;
          invoice_notes?: string | null;
          source?: string;
          ip_address?: string | null;
          user_agent?: string | null;
          coupon_id?: string | null;
          coupon_code?: string | null;
          gift_card_id?: string | null;
          gift_card_amount_used?: number;
          store_credit_used?: number;
          tracking_number?: string | null;
          tracking_url?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: number;
          user_id?: string | null;
          status?: "pending" | "confirmed" | "processing" | "packed" | "shipped" | "delivered" | "cancelled";
          payment_status?: "pending" | "authorized" | "paid" | "partially_refunded" | "refunded" | "failed";
          fulfillment_type?: "pickup" | "delivery" | "shipping";
          fulfillment_location_id?: string | null;
          delivery_zone_id?: string | null;
          shipping_zone_id?: string | null;
          schedule_id?: string | null;
          scheduled_date?: string | null;
          shipping_address?: Json | null;
          billing_address?: Json | null;
          subtotal?: number;
          discount_amount?: number;
          tax_amount?: number;
          shipping_fee?: number;
          total?: number;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          customer_notes?: string | null;
          private_notes?: string | null;
          invoice_notes?: string | null;
          source?: string;
          ip_address?: string | null;
          user_agent?: string | null;
          coupon_id?: string | null;
          coupon_code?: string | null;
          gift_card_id?: string | null;
          gift_card_amount_used?: number;
          store_credit_used?: number;
          tracking_number?: string | null;
          tracking_url?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string | null;
          variant_id: string | null;
          product_name: string;
          sku: string | null;
          quantity: number;
          unit_price: number;
          pricing_type: "fixed" | "weight";
          estimated_weight: number | null;
          actual_weight: number | null;
          final_price: number | null;
          is_packed: boolean;
          packed_at: string | null;
          packed_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id?: string | null;
          variant_id?: string | null;
          product_name: string;
          sku?: string | null;
          quantity?: number;
          unit_price: number;
          pricing_type?: "fixed" | "weight";
          estimated_weight?: number | null;
          actual_weight?: number | null;
          final_price?: number | null;
          is_packed?: boolean;
          packed_at?: string | null;
          packed_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          product_id?: string | null;
          variant_id?: string | null;
          product_name?: string;
          sku?: string | null;
          quantity?: number;
          unit_price?: number;
          pricing_type?: "fixed" | "weight";
          estimated_weight?: number | null;
          actual_weight?: number | null;
          final_price?: number | null;
          is_packed?: boolean;
          packed_at?: string | null;
          packed_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          name: string | null;
          status: "active" | "paused" | "cancelled" | "expired";
          frequency: "weekly" | "biweekly" | "monthly";
          fulfillment_type: "pickup" | "delivery" | "shipping";
          fulfillment_location_id: string | null;
          delivery_zone_id: string | null;
          shipping_zone_id: string | null;
          next_order_date: string | null;
          last_order_date: string | null;
          stripe_subscription_id: string | null;
          stripe_price_id: string | null;
          shipping_address: Json | null;
          skip_dates: string[];
          cancelled_at: string | null;
          cancellation_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name?: string | null;
          status?: "active" | "paused" | "cancelled" | "expired";
          frequency?: "weekly" | "biweekly" | "monthly";
          fulfillment_type: "pickup" | "delivery" | "shipping";
          fulfillment_location_id?: string | null;
          delivery_zone_id?: string | null;
          shipping_zone_id?: string | null;
          next_order_date?: string | null;
          last_order_date?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          shipping_address?: Json | null;
          skip_dates?: string[];
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string | null;
          status?: "active" | "paused" | "cancelled" | "expired";
          frequency?: "weekly" | "biweekly" | "monthly";
          fulfillment_type?: "pickup" | "delivery" | "shipping";
          fulfillment_location_id?: string | null;
          delivery_zone_id?: string | null;
          shipping_zone_id?: string | null;
          next_order_date?: string | null;
          last_order_date?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          shipping_address?: Json | null;
          skip_dates?: string[];
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      fulfillment_locations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          type: "pickup" | "delivery" | "shipping";
          description: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string;
          contact_name: string | null;
          contact_phone: string | null;
          contact_email: string | null;
          instructions: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          type: "pickup" | "delivery" | "shipping";
          description?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          contact_name?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          instructions?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          type?: "pickup" | "delivery" | "shipping";
          description?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          contact_name?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          instructions?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      delivery_zones: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          zip_codes: string[];
          delivery_fee: number;
          min_order_amount: number | null;
          free_delivery_threshold: number | null;
          pricing_tier_id: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          zip_codes?: string[];
          delivery_fee?: number;
          min_order_amount?: number | null;
          free_delivery_threshold?: number | null;
          pricing_tier_id?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          zip_codes?: string[];
          delivery_fee?: number;
          min_order_amount?: number | null;
          free_delivery_threshold?: number | null;
          pricing_tier_id?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      coupons: {
        Row: {
          id: string;
          code: string;
          description: string | null;
          coupon_type: "percentage" | "fixed" | "free_shipping";
          value: number;
          min_order_amount: number | null;
          max_discount_amount: number | null;
          max_uses: number | null;
          max_uses_per_user: number;
          used_count: number;
          valid_from: string | null;
          valid_until: string | null;
          is_active: boolean;
          applies_to_products: string[];
          applies_to_categories: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          description?: string | null;
          coupon_type: "percentage" | "fixed" | "free_shipping";
          value: number;
          min_order_amount?: number | null;
          max_discount_amount?: number | null;
          max_uses?: number | null;
          max_uses_per_user?: number;
          used_count?: number;
          valid_from?: string | null;
          valid_until?: string | null;
          is_active?: boolean;
          applies_to_products?: string[];
          applies_to_categories?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          description?: string | null;
          coupon_type?: "percentage" | "fixed" | "free_shipping";
          value?: number;
          min_order_amount?: number | null;
          max_discount_amount?: number | null;
          max_uses?: number | null;
          max_uses_per_user?: number;
          used_count?: number;
          valid_from?: string | null;
          valid_until?: string | null;
          is_active?: boolean;
          applies_to_products?: string[];
          applies_to_categories?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      gift_cards: {
        Row: {
          id: string;
          code: string;
          initial_balance: number;
          current_balance: number;
          purchased_by_user_id: string | null;
          purchase_order_id: string | null;
          redeemed_by_user_id: string | null;
          recipient_email: string | null;
          recipient_name: string | null;
          personal_message: string | null;
          is_active: boolean;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          initial_balance: number;
          current_balance: number;
          purchased_by_user_id?: string | null;
          purchase_order_id?: string | null;
          redeemed_by_user_id?: string | null;
          recipient_email?: string | null;
          recipient_name?: string | null;
          personal_message?: string | null;
          is_active?: boolean;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          initial_balance?: number;
          current_balance?: number;
          purchased_by_user_id?: string | null;
          purchase_order_id?: string | null;
          redeemed_by_user_id?: string | null;
          recipient_email?: string | null;
          recipient_name?: string | null;
          personal_message?: string | null;
          is_active?: boolean;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      settings: {
        Row: {
          key: string;
          value: Json;
          description: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          description?: string | null;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          description?: string | null;
          updated_at?: string;
        };
      };
      shipping_zones: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          states: string[];
          base_rate: number;
          per_lb_rate: number;
          min_order_amount: number | null;
          max_weight: number | null;
          free_shipping_minimum: number | null;
          carrier: "usps" | "ups" | "fedex" | "local";
          estimated_days_min: number | null;
          estimated_days_max: number | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          states?: string[];
          base_rate?: number;
          per_lb_rate?: number;
          min_order_amount?: number | null;
          max_weight?: number | null;
          free_shipping_minimum?: number | null;
          carrier?: "usps" | "ups" | "fedex" | "local";
          estimated_days_min?: number | null;
          estimated_days_max?: number | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          states?: string[];
          base_rate?: number;
          per_lb_rate?: number;
          min_order_amount?: number | null;
          max_weight?: number | null;
          free_shipping_minimum?: number | null;
          carrier?: "usps" | "ups" | "fedex" | "local";
          estimated_days_min?: number | null;
          estimated_days_max?: number | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      schedules: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          schedule_type: "recurring" | "one_time";
          recurrence_rule: Json | null;
          cutoff_hours_before: number;
          cutoff_time: string;
          available_dates: string[];
          blocked_dates: string[];
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          schedule_type?: "recurring" | "one_time";
          recurrence_rule?: Json | null;
          cutoff_hours_before?: number;
          cutoff_time?: string;
          available_dates?: string[];
          blocked_dates?: string[];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          schedule_type?: "recurring" | "one_time";
          recurrence_rule?: Json | null;
          cutoff_hours_before?: number;
          cutoff_time?: string;
          available_dates?: string[];
          blocked_dates?: string[];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      schedule_assignments: {
        Row: {
          id: string;
          schedule_id: string;
          fulfillment_location_id: string | null;
          delivery_zone_id: string | null;
          shipping_zone_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          schedule_id: string;
          fulfillment_location_id?: string | null;
          delivery_zone_id?: string | null;
          shipping_zone_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          schedule_id?: string;
          fulfillment_location_id?: string | null;
          delivery_zone_id?: string | null;
          shipping_zone_id?: string | null;
          created_at?: string;
        };
      };
      bundles: {
        Row: {
          id: string;
          product_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      bundle_items: {
        Row: {
          id: string;
          bundle_id: string;
          product_id: string;
          quantity: number;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          bundle_id: string;
          product_id: string;
          quantity?: number;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          bundle_id?: string;
          product_id?: string;
          quantity?: number;
          sort_order?: number;
          created_at?: string;
        };
      };
      product_variants: {
        Row: {
          id: string;
          product_id: string;
          name: string;
          sku: string | null;
          price_modifier: number;
          stock_quantity: number;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          name: string;
          sku?: string | null;
          price_modifier?: number;
          stock_quantity?: number;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          name?: string;
          sku?: string | null;
          price_modifier?: number;
          stock_quantity?: number;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      is_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      is_admin_or_staff: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
    };
    Enums: {
      user_role: "customer" | "staff" | "admin";
      pricing_type: "fixed" | "weight";
      weight_unit: "lb" | "oz" | "kg" | "g";
      order_status: "pending" | "confirmed" | "processing" | "packed" | "shipped" | "delivered" | "cancelled";
      payment_status: "pending" | "authorized" | "paid" | "partially_refunded" | "refunded" | "failed";
      fulfillment_type: "pickup" | "delivery" | "shipping";
      subscription_status: "active" | "paused" | "cancelled" | "expired";
      subscription_frequency: "weekly" | "biweekly" | "monthly";
      schedule_type: "recurring" | "one_time";
      coupon_type: "percentage" | "fixed" | "free_shipping";
      carrier_type: "usps" | "ups" | "fedex" | "local";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

// Helper types
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];

// Convenience type aliases
export type Profile = Tables<"profiles">;
export type Address = Tables<"addresses">;
export type Category = Tables<"categories">;
export type Product = Tables<"products">;
export type Order = Tables<"orders">;
export type OrderItem = Tables<"order_items">;
export type Subscription = Tables<"subscriptions">;
export type FulfillmentLocation = Tables<"fulfillment_locations">;
export type DeliveryZone = Tables<"delivery_zones">;
export type Coupon = Tables<"coupons">;
export type GiftCard = Tables<"gift_cards">;
export type Setting = Tables<"settings">;
